#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <time.h>
#include <pthread.h>
#include "sudoku_validator.h"

#define NUMBER_OF_THREADS 11
// #define NUMBER_OF_THREADS 27

int isValid = true;
pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;

// ============== Struct Definition ==============
typedef struct sudokuGridNode *sudokuGrid;
typedef struct sudokuGridNode
{
    int index;
    int (*sudoku)[COLUMNS];
} sudokuGridNode;

// ============== Function Prototypes ==============
void validateMultipleSodukoGrids();
bool validateSudoku(int[ROWS][COLUMNS]);
void *threadValidateRow(void *);
void *threadValidateColumn(void *);
void *threadValidateSubgrid(void *);

// ============== Main ==============
int main()
{

    int sudoku[25][25] = {
        {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25},
        {6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5},
        {11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
        {16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
        {21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20},
        {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1},
        {7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6},
        {12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
        {17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
        {22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21},
        {3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2},
        {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7},
        {13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12},
        {18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17},
        {23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22},
        {4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3},
        {9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8},
        {14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13},
        {19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18},
        {24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23},
        {5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4},
        {10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9},
        {15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
        {20, 21, 22, 23, 24, 25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19},
        {25, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}};

    printf("====================================\n");
    printf("\t11 Threads APPROACH");
    // printf("\t27 Threads APPROACH");
    // printf("\n\t      25x25x5");

    printf("\n====================================\n");

    clock_t start, end;
    double cpu_time_used;

    start = clock();
    validateMultipleSodukoGrids();

    // 25x25x25 approach test case
    /*

        if (validateSudoku(sudoku))
        {
            printf("✅ Valid\n");
        }
        else
        {
            printf("❌ Invalid\n");
        }

    */

    end = clock();

    cpu_time_used = ((double)(end - start)) / CLOCKS_PER_SEC;
    printf("\nTime taken in 11 Threads approach: %f seconds\n", cpu_time_used);
    // printf("\nTime taken in 27 Threads approach: %f seconds\n", cpu_time_used);

    printf("\n");
    printf("\n");

    return 0;
}

// function to test 10 sudoku grids (Generated by ChatGPT - just this function because obviously i won't think of 10 diffenret sudokus grid (: ))
void validateMultipleSodukoGrids()
{
    int sudoku1[ROWS][COLUMNS] = {
        {5, 3, 4, 6, 7, 8, 9, 1, 2},
        {6, 7, 2, 1, 9, 5, 3, 4, 8},
        {1, 9, 8, 3, 4, 2, 5, 6, 7},
        {8, 5, 9, 7, 6, 1, 4, 2, 3},
        {4, 2, 6, 8, 5, 3, 7, 9, 1},
        {7, 1, 3, 9, 2, 4, 8, 5, 6},
        {9, 6, 1, 5, 3, 7, 2, 8, 4},
        {2, 8, 7, 4, 1, 9, 6, 3, 5},
        {3, 4, 5, 2, 8, 6, 1, 7, 9}};
    // --- Array 2 ---
    int sudoku2[ROWS][COLUMNS] = {
        {5, 3, 4, 5, 7, 8, 9, 1, 2},
        {6, 7, 2, 1, 9, 5, 3, 4, 8},
        {1, 9, 8, 3, 4, 2, 5, 6, 7},
        {8, 5, 9, 7, 6, 1, 4, 2, 3},
        {4, 2, 6, 8, 5, 3, 7, 9, 1},
        {7, 1, 3, 9, 2, 4, 8, 5, 6},
        {9, 6, 1, 5, 3, 7, 2, 8, 4},
        {2, 8, 7, 4, 1, 9, 6, 3, 5},
        {3, 4, 5, 2, 8, 6, 1, 7, 9}};
    // --- Array 3 ---
    int sudoku3[ROWS][COLUMNS] = {
        {8, 2, 7, 1, 5, 4, 3, 9, 6},
        {9, 6, 5, 3, 2, 7, 1, 4, 8},
        {3, 4, 1, 6, 8, 9, 7, 5, 2},
        {5, 9, 3, 4, 6, 8, 2, 7, 1},
        {4, 7, 2, 5, 1, 3, 6, 8, 9},
        {6, 1, 8, 9, 7, 2, 4, 3, 5},
        {7, 8, 6, 2, 3, 5, 9, 1, 4},
        {1, 5, 4, 7, 9, 6, 8, 2, 3},
        {2, 3, 9, 8, 4, 1, 5, 6, 7}};
    // --- Array 4 ---
    int sudoku4[ROWS][COLUMNS] = {
        {8, 2, 7, 1, 5, 4, 3, 9, 6},
        {9, 6, 5, 3, 2, 7, 1, 4, 8},
        {3, 4, 1, 6, 8, 9, 7, 5, 2},
        {5, 9, 3, 4, 6, 8, 2, 7, 1},
        {4, 7, 2, 5, 1, 3, 6, 8, 9},
        {6, 1, 8, 9, 7, 2, 4, 3, 5},
        {7, 8, 6, 2, 3, 5, 9, 1, 4},
        {1, 5, 4, 7, 9, 6, 8, 2, 3},
        {2, 3, 7, 8, 4, 1, 5, 6, 7} // Invalid here
    };
    // --- Array 5 ---
    int sudoku5[ROWS][COLUMNS] = {
        {5, 3, 4, 6, 7, 8, 9, 1, 2},
        {6, 7, 2, 1, 9, 5, 3, 4, 8},
        {1, 9, 8, 3, 4, 2, 5, 6, 7},
        {8, 5, 9, 7, 6, 1, 4, 2, 3},
        {4, 2, 6, 8, 5, 3, 7, 0, 1}, // 0 instead of 9
        {7, 1, 3, 9, 2, 4, 8, 5, 6},
        {9, 6, 1, 5, 3, 7, 2, 8, 4},
        {2, 8, 7, 4, 1, 9, 6, 3, 5},
        {3, 4, 5, 2, 8, 6, 1, 7, 9}};
    // --- Array 6 ---
    int sudoku6[ROWS][COLUMNS] = {
        {1, 2, 3, 4, 5, 6, 7, 8, 9},
        {4, 5, 6, 7, 8, 9, 1, 2, 3},
        {7, 8, 9, 1, 2, 3, 4, 5, 6},
        {2, 3, 1, 5, 6, 4, 8, 9, 7},
        {5, 6, 4, 8, 9, 7, 2, 3, 1},
        {8, 9, 7, 2, 3, 1, 5, 6, 4},
        {3, 1, 2, 6, 4, 5, 9, 7, 8},
        {6, 4, 5, 9, 7, 8, 3, 1, 2},
        {9, 7, 8, 3, 1, 2, 6, 4, 5}};
    // --- Array 7 ---
    int sudoku7[ROWS][COLUMNS] = {
        {1, 2, 3, 4, 5, 6, 7, 8, 9},
        {4, 5, 6, 7, 8, 9, 1, 2, 3},
        {7, 8, 9, 1, 2, 3, 4, 5, 6},
        {2, 3, 1, 5, 6, 4, 8, 9, 7},
        {5, 6, 4, 8, 9, 7, 2, 3, 1},
        {8, 9, 7, 2, 3, 1, 5, 6, 4},
        {3, 1, 2, 6, 4, 5, 9, 7, 8},
        {6, 4, 5, 9, 7, 8, 3, 1, 2},
        {9, 7, 8, 3, 1, 2, 6, 4, 4} // Invalid duplicate
    };
    // --- Array 8 ---
    int sudoku8[ROWS][COLUMNS] = {
        {2, 7, 6, 3, 1, 9, 5, 8, 4},
        {9, 5, 1, 6, 4, 8, 7, 3, 2},
        {4, 8, 3, 2, 7, 5, 9, 1, 6},
        {5, 2, 9, 1, 8, 6, 3, 4, 7},
        {7, 1, 8, 9, 3, 4, 6, 2, 5},
        {6, 3, 4, 5, 2, 7, 1, 9, 8},
        {1, 6, 2, 8, 5, 3, 4, 7, 9},
        {8, 9, 5, 7, 6, 2, 2, 5, 1},
        {3, 4, 7, 4, 9, 1, 8, 6, 2}};
    // --- Array 9 ---
    int sudoku9[ROWS][COLUMNS] = {
        {2, 7, 6, 3, 1, 9, 5, 8, 4},
        {9, 5, 1, 6, 4, 8, 7, 3, 2},
        {4, 8, 3, 2, 7, 5, 9, 1, 6},
        {5, 2, 9, 1, 8, 6, 3, 4, 7},
        {7, 1, 8, 9, 3, 4, 6, 2, 5},
        {6, 3, 4, 5, 2, 7, 1, 9, 8},
        {1, 6, 2, 8, 5, 3, 4, 7, 9},
        {8, 9, 5, 7, 6, 2, 2, 5, 1},
        {3, 4, 7, 4, 9, 1, 8, 6, 2}};
    // --- Array 10 (new valid one) ---
    int sudoku10[ROWS][COLUMNS] = {
        {8, 2, 7, 1, 5, 4, 3, 9, 6},
        {9, 6, 5, 3, 2, 7, 1, 4, 8},
        {3, 4, 1, 6, 8, 9, 7, 5, 2},
        {5, 9, 3, 4, 6, 8, 2, 7, 1},
        {4, 7, 2, 5, 1, 3, 6, 8, 9},
        {6, 1, 8, 9, 7, 2, 4, 3, 5},
        {7, 8, 6, 2, 3, 5, 9, 1, 4},
        {1, 5, 4, 7, 9, 6, 8, 2, 3},
        {2, 3, 9, 8, 4, 1, 5, 6, 7}};

    // Array of pointers to all sudoku boards
    int (*sudokus[10])[ROWS][COLUMNS] = {&sudoku1, &sudoku2, &sudoku3, &sudoku4, &sudoku5, &sudoku6, &sudoku7, &sudoku8, &sudoku9, &sudoku10};

    for (int i = 0; i < 10; i++)
    {
        printf("Testing sudoku%d: ", i + 1);
        if (validateSudoku(*sudokus[i]))
        {
            printf("✅ Valid\n");
        }
        else
        {
            printf("❌ Invalid\n");
        }
    }
}

// ============== Thread Functions ==============
void *threadValidateRow(void *param)
{
    sudokuGrid sg = (sudokuGrid)(param);
    for (int i = 0; i < ROWS; i++)
    {
        if (!validateRow(i, sg->sudoku))
        {
            isValid = false;
        }
    }
    pthread_exit(0);
}

void *threadValidateColumn(void *param)
{
    sudokuGrid sg = (sudokuGrid)(param);
    for (int i = 0; i < COLUMNS; i++)
    {
        if (!validateColumn(i, sg->sudoku))
        {
            isValid = false;
        }
    }
    pthread_exit(0);
}

void *threadValidateSubgrid(void *param)
{
    sudokuGrid sg = (sudokuGrid)(param);
    int row = (sg->index / SUBGRID);
    int col = (sg->index % SUBGRID);

    // sg->index / SUBGRID, sg->index % SUBGRID

    if (!validateSubgrid(row, col, sg->sudoku))
    {
        isValid = false;
    }
    pthread_exit(0);
}

// ============== Main Validation Function ==============
bool validateSudoku(int sudoku[ROWS][COLUMNS])
{
    isValid = true;

    pthread_t threads[NUMBER_OF_THREADS];
    pthread_attr_t attr;

    pthread_attr_init(&attr);

    for (int i = 0; i < NUMBER_OF_THREADS; i++)
    {
        sudokuGrid sg = malloc(sizeof(sudokuGridNode));
        sg->sudoku = sudoku;

        if (i == 0)
        {
            sg->index = 0;
            pthread_create(&threads[i], &attr, threadValidateRow, sg);
        }

        else if (i == 1)
        {
            sg->index = 0;
            pthread_create(&threads[i], &attr, threadValidateColumn, sg);
        }
        else
        {
            sg->index = i - 2;
            pthread_create(&threads[i], &attr, threadValidateSubgrid, sg);
        }
    }

    for (int i = 0; i < NUMBER_OF_THREADS; i++)
    {
        pthread_join(threads[i], NULL);
    }

    return isValid;
}