#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <time.h>
#include "sudoku_validator.h"
#include <pthread.h>

#define NUMBER_OF_THREADS 27

// ======================== Functions ========================
void validateMultipleSodukoGrids();
bool validateSudoku(int[ROWS][COLUMNS]);
void *threadValidateRow(void *);
void *threadValidateColumn(void *);
void *threadValidateSubgrid(void *);
// ======================== Functions ========================

typedef struct sudokuGridNode *sudokuGrid;

typedef struct sudokuGridNode
{
    int index;
    int (*sudoku)[COLUMNS];
};

int main()
{

    clock_t start, end;
    double cpu_time_used;

    start = clock();
    validateMultipleSodukoGrids();
    end = clock();

    cpu_time_used = ((double)(end - start)) / CLOCKS_PER_SEC;
    printf("\nTime taken: %f seconds\n", cpu_time_used);

    printf("\n");
    printf("\n");
    return 0;
}

// function to test 10 sudoku grids (Generated by ChatGPT - just this function because obviously i won'y think of diffenret sudokus grid (: ))
void validateMultipleSodukoGrids()
{
    int sudoku1[ROWS][COLUMNS] = {
        {5, 3, 4, 6, 7, 8, 9, 1, 2},
        {6, 7, 2, 1, 9, 5, 3, 4, 8},
        {1, 9, 8, 3, 4, 2, 5, 6, 7},
        {8, 5, 9, 7, 6, 1, 4, 2, 3},
        {4, 2, 6, 8, 5, 3, 7, 9, 1},
        {7, 1, 3, 9, 2, 4, 8, 5, 6},
        {9, 6, 1, 5, 3, 7, 2, 8, 4},
        {2, 8, 7, 4, 1, 9, 6, 3, 5},
        {3, 4, 5, 2, 8, 6, 1, 7, 9}};
    // --- Array 2 ---
    int sudoku2[ROWS][COLUMNS] = {
        {5, 3, 4, 5, 7, 8, 9, 1, 2},
        {6, 7, 2, 1, 9, 5, 3, 4, 8},
        {1, 9, 8, 3, 4, 2, 5, 6, 7},
        {8, 5, 9, 7, 6, 1, 4, 2, 3},
        {4, 2, 6, 8, 5, 3, 7, 9, 1},
        {7, 1, 3, 9, 2, 4, 8, 5, 6},
        {9, 6, 1, 5, 3, 7, 2, 8, 4},
        {2, 8, 7, 4, 1, 9, 6, 3, 5},
        {3, 4, 5, 2, 8, 6, 1, 7, 9}};
    // --- Array 3 ---
    int sudoku3[ROWS][COLUMNS] = {
        {8, 2, 7, 1, 5, 4, 3, 9, 6},
        {9, 6, 5, 3, 2, 7, 1, 4, 8},
        {3, 4, 1, 6, 8, 9, 7, 5, 2},
        {5, 9, 3, 4, 6, 8, 2, 7, 1},
        {4, 7, 2, 5, 1, 3, 6, 8, 9},
        {6, 1, 8, 9, 7, 2, 4, 3, 5},
        {7, 8, 6, 2, 3, 5, 9, 1, 4},
        {1, 5, 4, 7, 9, 6, 8, 2, 3},
        {2, 3, 9, 8, 4, 1, 5, 6, 7}};
    // --- Array 4 ---
    int sudoku4[ROWS][COLUMNS] = {
        {8, 2, 7, 1, 5, 4, 3, 9, 6},
        {9, 6, 5, 3, 2, 7, 1, 4, 8},
        {3, 4, 1, 6, 8, 9, 7, 5, 2},
        {5, 9, 3, 4, 6, 8, 2, 7, 1},
        {4, 7, 2, 5, 1, 3, 6, 8, 9},
        {6, 1, 8, 9, 7, 2, 4, 3, 5},
        {7, 8, 6, 2, 3, 5, 9, 1, 4},
        {1, 5, 4, 7, 9, 6, 8, 2, 3},
        {2, 3, 7, 8, 4, 1, 5, 6, 7} // Invalid here
    };
    // --- Array 5 ---
    int sudoku5[ROWS][COLUMNS] = {
        {5, 3, 4, 6, 7, 8, 9, 1, 2},
        {6, 7, 2, 1, 9, 5, 3, 4, 8},
        {1, 9, 8, 3, 4, 2, 5, 6, 7},
        {8, 5, 9, 7, 6, 1, 4, 2, 3},
        {4, 2, 6, 8, 5, 3, 7, 0, 1}, // 0 instead of 9
        {7, 1, 3, 9, 2, 4, 8, 5, 6},
        {9, 6, 1, 5, 3, 7, 2, 8, 4},
        {2, 8, 7, 4, 1, 9, 6, 3, 5},
        {3, 4, 5, 2, 8, 6, 1, 7, 9}};
    // --- Array 6 ---
    int sudoku6[ROWS][COLUMNS] = {
        {1, 2, 3, 4, 5, 6, 7, 8, 9},
        {4, 5, 6, 7, 8, 9, 1, 2, 3},
        {7, 8, 9, 1, 2, 3, 4, 5, 6},
        {2, 3, 1, 5, 6, 4, 8, 9, 7},
        {5, 6, 4, 8, 9, 7, 2, 3, 1},
        {8, 9, 7, 2, 3, 1, 5, 6, 4},
        {3, 1, 2, 6, 4, 5, 9, 7, 8},
        {6, 4, 5, 9, 7, 8, 3, 1, 2},
        {9, 7, 8, 3, 1, 2, 6, 4, 5}};
    // --- Array 7 ---
    int sudoku7[ROWS][COLUMNS] = {
        {1, 2, 3, 4, 5, 6, 7, 8, 9},
        {4, 5, 6, 7, 8, 9, 1, 2, 3},
        {7, 8, 9, 1, 2, 3, 4, 5, 6},
        {2, 3, 1, 5, 6, 4, 8, 9, 7},
        {5, 6, 4, 8, 9, 7, 2, 3, 1},
        {8, 9, 7, 2, 3, 1, 5, 6, 4},
        {3, 1, 2, 6, 4, 5, 9, 7, 8},
        {6, 4, 5, 9, 7, 8, 3, 1, 2},
        {9, 7, 8, 3, 1, 2, 6, 4, 4} // Invalid duplicate
    };
    // --- Array 8 ---
    int sudoku8[ROWS][COLUMNS] = {
        {2, 7, 6, 3, 1, 9, 5, 8, 4},
        {9, 5, 1, 6, 4, 8, 7, 3, 2},
        {4, 8, 3, 2, 7, 5, 9, 1, 6},
        {5, 2, 9, 1, 8, 6, 3, 4, 7},
        {7, 1, 8, 9, 3, 4, 6, 2, 5},
        {6, 3, 4, 5, 2, 7, 1, 9, 8},
        {1, 6, 2, 8, 5, 3, 4, 7, 9},
        {8, 9, 5, 7, 6, 2, 2, 5, 1},
        {3, 4, 7, 4, 9, 1, 8, 6, 2}};
    // --- Array 9 ---
    int sudoku9[ROWS][COLUMNS] = {
        {2, 7, 6, 3, 1, 9, 5, 8, 4},
        {9, 5, 1, 6, 4, 8, 7, 3, 2},
        {4, 8, 3, 2, 7, 5, 9, 1, 6},
        {5, 2, 9, 1, 8, 6, 3, 4, 7},
        {7, 1, 8, 9, 3, 4, 6, 2, 5},
        {6, 3, 4, 5, 2, 7, 1, 9, 8},
        {1, 6, 2, 8, 5, 3, 4, 7, 9},
        {8, 9, 5, 7, 6, 2, 2, 5, 1},
        {3, 4, 7, 4, 9, 1, 8, 6, 2}};
    // --- Array 10 (new valid one) ---
    int sudoku10[ROWS][COLUMNS] = {
        {8, 2, 7, 1, 5, 4, 3, 9, 6},
        {9, 6, 5, 3, 2, 7, 1, 4, 8},
        {3, 4, 1, 6, 8, 9, 7, 5, 2},
        {5, 9, 3, 4, 6, 8, 2, 7, 1},
        {4, 7, 2, 5, 1, 3, 6, 8, 9},
        {6, 1, 8, 9, 7, 2, 4, 3, 5},
        {7, 8, 6, 2, 3, 5, 9, 1, 4},
        {1, 5, 4, 7, 9, 6, 8, 2, 3},
        {2, 3, 9, 8, 4, 1, 5, 6, 7}};

    // Array of pointers to all sudoku boards
    int (*sudokus[10])[ROWS][COLUMNS] = {&sudoku1, &sudoku2, &sudoku3, &sudoku4, &sudoku5, &sudoku6, &sudoku7, &sudoku8, &sudoku9, &sudoku10};

    for (int i = 0; i < 10; i++)
    {
        printf("Testing sudoku%d: ", i + 1);
        if (validateSudoku(*sudokus[i]))
        {
            printf("✅ Valid\n");
        }
        else
        {
            printf("❌ Invalid\n");
        }
    }
}

bool validateSudoku(int sudoku[ROWS][COLUMNS])
{
    // reinitialize the global variables
    isValid = true;

    pthread_t threads[NUMBER_OF_THREADS];           // the thread identifiers
    pthread_attr_t threads_attr[NUMBER_OF_THREADS]; // set of thread attributes

    for (int i = 0; i < NUMBER_OF_THREADS; i++)
    {
        pthread_attr_init(&threads_attr[i]);                               // set the default attributes of the thread
        sudokuGrid sg = (sudokuGrid)malloc(sizeof(struct sudokuGridNode)); // create the threads
        // thread can only take (void *), so all the args i need to put in a struct
        sg->index = i % (NUMBER_OF_THREADS / 3); // '3' options, row, column and subgrid
        sg->sudoku = sudoku;
        if (i < (NUMBER_OF_THREADS / 3))
        {
            pthread_create(&threads[i], &threads_attr[i], threadValidateRow, sg); // sends the first batch of threds
        }
        else if (i < 2 * (NUMBER_OF_THREADS / 3))
        {
            pthread_create(&threads[i], &threads_attr[i], threadValidateColumn, sg); // sends the second batch of threds
        }

        else
        {
            pthread_create(&threads[i], &threads_attr[i], threadValidateSubgrid, sg); // sends the third batch of threds
        }
    }

    for (int i = 0; i < NUMBER_OF_THREADS; i++)
    {
        pthread_join(threads[i], NULL); // wait until each thread finished
    }

    return isValid;
}

void *threadValidateRow(void *param)
{
    sudokuGrid sg = (sudokuGrid)(param); // cast the 'sg' to get its args
    if (!validateRow(sg->index, sg->sudoku))
    {
        isValid = false;
    }

    pthread_exit(0);
}

void *threadValidateColumn(void *param)
{
    sudokuGrid sg = (sudokuGrid)(param); // cast the 'sg' to get its args
    if (!validateColumn(sg->index, sg->sudoku))
    {
        isValid = false;
    }
    pthread_exit(0);
}

void *threadValidateSubgrid(void *param)
{
    sudokuGrid sg = (sudokuGrid)(param); // cast the 'sg' to get its args
    // an equation that convert from 012345678 -> 00 01 02 10 11 12 20 21 22
    if (!validateSubgrid(sg->index / SUBGRID, sg->index % SUBGRID, sg->sudoku)) // takes ROW,COLUMN
    {
        isValid = false;
    }
    pthread_exit(0);
}
