#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <time.h>
#include "sudoku_validator.h"

// ======================== Functions ========================
void printsudoku(int[ROWS][COLUMNS]);
void printSubgrid(int, int, int[ROWS][COLUMNS]);
bool validateRow(int, int[ROWS][COLUMNS]);
bool validateColumn(int, int[ROWS][COLUMNS]);
bool validateAllSubgrids(int[ROWS][COLUMNS]);
bool validateSubgrid(int, int, int[ROWS][COLUMNS]);
bool validatesudoku(int[ROWS][COLUMNS]);
bool validateAllRows(int[ROWS][COLUMNS]);
bool validateALLColumns(int[ROWS][COLUMNS]);
void validateMultipleSodukoGrids();
// ======================== Functions ========================

int main()
{

    clock_t start, end;
    double cpu_time_used;

    start = clock();
    validateMultipleSodukoGrids();
    end = clock();

    cpu_time_used = ((double)(end - start)) / CLOCKS_PER_SEC;
    printf("\nTime taken: %f seconds\n", cpu_time_used);

    printf("\n");
    printf("\n");
    return 0;
}

// generated by ChatGPT
void validateMultipleSodukoGrids()
{
    int sudoku1[ROWS][COLUMNS] = {
        {5, 3, 4, 6, 7, 8, 9, 1, 2},
        {6, 7, 2, 1, 9, 5, 3, 4, 8},
        {1, 9, 8, 3, 4, 2, 5, 6, 7},
        {8, 5, 9, 7, 6, 1, 4, 2, 3},
        {4, 2, 6, 8, 5, 3, 7, 9, 1},
        {7, 1, 3, 9, 2, 4, 8, 5, 6},
        {9, 6, 1, 5, 3, 7, 2, 8, 4},
        {2, 8, 7, 4, 1, 9, 6, 3, 5},
        {3, 4, 5, 2, 8, 6, 1, 7, 9}};
    // --- Array 2 ---
    int sudoku2[ROWS][COLUMNS] = {
        {5, 3, 4, 5, 7, 8, 9, 1, 2},
        {6, 7, 2, 1, 9, 5, 3, 4, 8},
        {1, 9, 8, 3, 4, 2, 5, 6, 7},
        {8, 5, 9, 7, 6, 1, 4, 2, 3},
        {4, 2, 6, 8, 5, 3, 7, 9, 1},
        {7, 1, 3, 9, 2, 4, 8, 5, 6},
        {9, 6, 1, 5, 3, 7, 2, 8, 4},
        {2, 8, 7, 4, 1, 9, 6, 3, 5},
        {3, 4, 5, 2, 8, 6, 1, 7, 9}};
    // --- Array 3 ---
    int sudoku3[ROWS][COLUMNS] = {
        {8, 2, 7, 1, 5, 4, 3, 9, 6},
        {9, 6, 5, 3, 2, 7, 1, 4, 8},
        {3, 4, 1, 6, 8, 9, 7, 5, 2},
        {5, 9, 3, 4, 6, 8, 2, 7, 1},
        {4, 7, 2, 5, 1, 3, 6, 8, 9},
        {6, 1, 8, 9, 7, 2, 4, 3, 5},
        {7, 8, 6, 2, 3, 5, 9, 1, 4},
        {1, 5, 4, 7, 9, 6, 8, 2, 3},
        {2, 3, 9, 8, 4, 1, 5, 6, 7}};
    // --- Array 4 ---
    int sudoku4[ROWS][COLUMNS] = {
        {8, 2, 7, 1, 5, 4, 3, 9, 6},
        {9, 6, 5, 3, 2, 7, 1, 4, 8},
        {3, 4, 1, 6, 8, 9, 7, 5, 2},
        {5, 9, 3, 4, 6, 8, 2, 7, 1},
        {4, 7, 2, 5, 1, 3, 6, 8, 9},
        {6, 1, 8, 9, 7, 2, 4, 3, 5},
        {7, 8, 6, 2, 3, 5, 9, 1, 4},
        {1, 5, 4, 7, 9, 6, 8, 2, 3},
        {2, 3, 7, 8, 4, 1, 5, 6, 7} // Invalid here
    };
    // --- Array 5 ---
    int sudoku5[ROWS][COLUMNS] = {
        {5, 3, 4, 6, 7, 8, 9, 1, 2},
        {6, 7, 2, 1, 9, 5, 3, 4, 8},
        {1, 9, 8, 3, 4, 2, 5, 6, 7},
        {8, 5, 9, 7, 6, 1, 4, 2, 3},
        {4, 2, 6, 8, 5, 3, 7, 0, 1}, // 0 instead of 9
        {7, 1, 3, 9, 2, 4, 8, 5, 6},
        {9, 6, 1, 5, 3, 7, 2, 8, 4},
        {2, 8, 7, 4, 1, 9, 6, 3, 5},
        {3, 4, 5, 2, 8, 6, 1, 7, 9}};
    // --- Array 6 ---
    int sudoku6[ROWS][COLUMNS] = {
        {1, 2, 3, 4, 5, 6, 7, 8, 9},
        {4, 5, 6, 7, 8, 9, 1, 2, 3},
        {7, 8, 9, 1, 2, 3, 4, 5, 6},
        {2, 3, 1, 5, 6, 4, 8, 9, 7},
        {5, 6, 4, 8, 9, 7, 2, 3, 1},
        {8, 9, 7, 2, 3, 1, 5, 6, 4},
        {3, 1, 2, 6, 4, 5, 9, 7, 8},
        {6, 4, 5, 9, 7, 8, 3, 1, 2},
        {9, 7, 8, 3, 1, 2, 6, 4, 5}};
    // --- Array 7 ---
    int sudoku7[ROWS][COLUMNS] = {
        {1, 2, 3, 4, 5, 6, 7, 8, 9},
        {4, 5, 6, 7, 8, 9, 1, 2, 3},
        {7, 8, 9, 1, 2, 3, 4, 5, 6},
        {2, 3, 1, 5, 6, 4, 8, 9, 7},
        {5, 6, 4, 8, 9, 7, 2, 3, 1},
        {8, 9, 7, 2, 3, 1, 5, 6, 4},
        {3, 1, 2, 6, 4, 5, 9, 7, 8},
        {6, 4, 5, 9, 7, 8, 3, 1, 2},
        {9, 7, 8, 3, 1, 2, 6, 4, 4} // Invalid duplicate
    };
    // --- Array 8 ---
    int sudoku8[ROWS][COLUMNS] = {
        {2, 7, 6, 3, 1, 9, 5, 8, 4},
        {9, 5, 1, 6, 4, 8, 7, 3, 2},
        {4, 8, 3, 2, 7, 5, 9, 1, 6},
        {5, 2, 9, 1, 8, 6, 3, 4, 7},
        {7, 1, 8, 9, 3, 4, 6, 2, 5},
        {6, 3, 4, 5, 2, 7, 1, 9, 8},
        {1, 6, 2, 8, 5, 3, 4, 7, 9},
        {8, 9, 5, 7, 6, 2, 2, 5, 1},
        {3, 4, 7, 4, 9, 1, 8, 6, 2}};
    // --- Array 9 ---
    int sudoku9[ROWS][COLUMNS] = {
        {2, 7, 6, 3, 1, 9, 5, 8, 4},
        {9, 5, 1, 6, 4, 8, 7, 3, 2},
        {4, 8, 3, 2, 7, 5, 9, 1, 6},
        {5, 2, 9, 1, 8, 6, 3, 4, 7},
        {7, 1, 8, 9, 3, 4, 6, 2, 5},
        {6, 3, 4, 5, 2, 7, 1, 9, 8},
        {1, 6, 2, 8, 5, 3, 4, 7, 9},
        {8, 9, 5, 7, 6, 2, 2, 5, 1},
        {3, 4, 7, 4, 9, 1, 8, 6, 2}};
    // --- Array 10 (new valid one) ---
    int sudoku10[ROWS][COLUMNS] = {
        {8, 2, 7, 1, 5, 4, 3, 9, 6},
        {9, 6, 5, 3, 2, 7, 1, 4, 8},
        {3, 4, 1, 6, 8, 9, 7, 5, 2},
        {5, 9, 3, 4, 6, 8, 2, 7, 1},
        {4, 7, 2, 5, 1, 3, 6, 8, 9},
        {6, 1, 8, 9, 7, 2, 4, 3, 5},
        {7, 8, 6, 2, 3, 5, 9, 1, 4},
        {1, 5, 4, 7, 9, 6, 8, 2, 3},
        {2, 3, 9, 8, 4, 1, 5, 6, 7}};

    // Array of pointers to all sudoku boards
    int (*sudokus[10])[ROWS][COLUMNS] = {&sudoku1, &sudoku2, &sudoku3, &sudoku4, &sudoku5, &sudoku6, &sudoku7, &sudoku8, &sudoku9, &sudoku10};

    for (int i = 0; i < 10; i++)
    {
        printf("Testing sudoku%d: ", i + 1);
        if (validatesudoku(*sudokus[i]))
        {
            printf("✅ Valid\n");
        }
        else
        {
            printf("❌ Invalid\n");
        }
    }
}

bool validatesudoku(int sudoku[ROWS][COLUMNS])
{
    return (validateAllRows(sudoku) && validateALLColumns(sudoku) && validateAllSubgrids(sudoku));
}

bool validateAllRows(int sudoku[ROWS][COLUMNS])
{
    for (int i = 0; i < ROWS; i++)
    {
        if (!validateRow(i, sudoku))
        {
            return false;
        }
    }
    return true;
}

bool validateALLColumns(int sudoku[ROWS][COLUMNS])
{
    for (int j = 0; j < COLUMNS; j++)
    {
        if (!validateColumn(j, sudoku))
        {
            return false;
        }
    }
    return true;
}

bool validateAllSubgrids(int sudoku[ROWS][COLUMNS])
{
    for (int i = 0; i < SUBGRID; i++)
    {
        for (int j = 0; j < SUBGRID; j++)
        {
            if (!validateSubgrid(i, j, sudoku))
            {
                printf("Error with Subgrid: (%d,%d)", i, j);
                return false;
            }
        }
    }
    return true;
}
